#!/usr/bin/env bash

set -e

source "${HOME}/.profile.d/env.d/fastmail.env"

CLOUDDIR="${FASTMAIL_HOME}/backup"
PACK="${CLOUDDIR}/dotfiles/$(date +%Y%m%d-%H%M%S)-${HOSTNAME}.tar.xz"

mkdir -p "$(dirname ${PACK})"

( cd "${HOME}/Sources/dotfiles"
  git ls-files | tar --create --preserve-permissions --xz --file="${PACK}" --directory="${HOME}" --files-from=-
)

echo "$(groups ${USER})" > "${CLOUDDIR}/dotfiles/groups.list"
cp "${PACK}" "${CLOUDDIR}/dotfiles-${HOSTNAME}.tar.xz"
