#!/usr/bin/bash
set -e

SPAN_S='<span foreground="black" background="white">'
SPAN_E='</span>'

CAL=$(cal --color=always          \
      | sed "s|\[7m|${SPAN_S}|" \
      | sed "s|\[0m|${SPAN_E}|");

TITLE="$(date '+%a, %d %B %Y %H:%M')" notify "\n${CAL}"
