#!/usr/bin/bash
set -e

CAL=$(cal --color=always \
      | sed 's|\[7m|<span foreground="black" background="white">|' \
      | sed 's|\[0m|</span>|')

TITLE="$(date '+%a, %d %B %Y %H:%M')" notify "\n${CAL}"
