#!/usr/bin/env bash

# Default audio source
asource="$(pactl list short sources | head -1 | awk '{ print $2 }')"
# Default video source
vsource="/dev/video0"
# Record name
output="${XDG_VIDEOS_DIR}/Camrec/${1:-record-$(date '+%Y%m%d-%H%M%S')}.mp4"

# Do the job
ffmpeg -y -f pulse -ac 2 -i "${asource}"      \
          -f v4l2        -i "${vsource}"      \
          -c:v libx264 -preset medium -crf 23 \
          -c:a aac -b:a 128k                  \
          "${output}"
