#!/usr/bin/env bash

set -e

THIS="$(basename ${BASH_SOURCE[0]})"

function usage() {
    echo "usage: ${THIS} profile [extra rclone options]"
    exit 1
}

[[ ${#} < 1 ]] && usage

case "${1}" in
    -*)
        usage
        ;;
    *)
        PROFILE="${1}"
        shift
        ;;
esac

CFG_FILE="${XDG_CONFIG_HOME}/rclone/${PROFILE}.conf"
LOG_FILE="${XDG_LOG_HOME}/rclone/${PROFILE}.log"

if [[ ! -r "${CFG_FILE}" ]]; then
    echo "[${THIS}]: invalid profile '${PROFILE}'"
    usage
fi

source "${HOME}/.profile.d/env.d/xdg.env"
source "${HOME}/.profile.d/env.d/${PROFILE}.env"

LOCAL_PATH="${PROFILE^^}_HOME"
LOCAL_PATH="${!LOCAL_PATH}"
REMOTE_PATH="${PROFILE^^}_PATH"
REMOTE_PATH="drive:${!REMOTE_PATH}"
CHECK_FILE=".gitkeep"
echo "[${THIS}]: local '${LOCAL_PATH}', remote '${REMOTE_PATH}', check file '${CHECK_FILE}'"

mkdir -p "${LOCAL_PATH}" "$(dirname ${LOG_FILE})"
if [[ -f "${LOCAL_PATH}/${CHECK_FILE}" ]]; then
    source "${LOCAL_PATH}/${CHECK_FILE}"
    [[ "${INIT}" ]] && (>"${LOCAL_PATH}/${CHECK_FILE}")
else
    echo "INIT=--resync" > "${LOCAL_PATH}/${CHECK_FILE}"
    INIT="--resync --dry-run"
fi
[[ "${INIT}" ]] && echo "[${THIS}]: init option(s) '${INIT}'"

exec rclone bisync --config="${CFG_FILE}"            \
                   --compare="size,modtime,checksum" \
                   --check-filename="${CHECK_FILE}"  \
                   --log-file="${LOG_FILE}"          \
                   --create-empty-src-dirs           \
                   --slow-hash-sync-only             \
                   --log-level INFO                  \
                   --check-access                    \
                   --resilient                       \
                   --metadata                        \
                   --fix-case                        \
                   "${LOCAL_PATH}"                   \
                   "${REMOTE_PATH}"                  \
                   ${INIT} "${@}"
