#!/usr/bin/env bash

IFS=$'\n'

fpath="${1/%\/}"
dpath="$(dirname "${fpath}")"

exec feh --auto-rotate --borderless  \
     --draw-filename --draw-tinted   \
     --hide-pointer --image-bg=black \
     --scale-down --start-at "${fpath}" "${dpath}" >/dev/null
