#!/usr/bin/bash -e

path="${1:-$(pwd)}"

# Strip 'file://' prefix
[[ "${path}" =~ ^file://(.*) ]] && {
    path="${BASH_REMATCH[1]}"
}

# Resolve relative path
realpath="$(realpath -e -s "${path}" 2>/dev/null)" || {
    notify "Invalid path: ${path}"
    exit 1
}

# Target must point to directory
[[ -d "${realpath}" ]] || {
  realpath="$(dirname "${realpath}")"
}

exec terminal -e "${FILEMAN}" "${realpath}" &
