#!/usr/bin/env bash

path="$(realpath --no-symlinks "${1:-$(pwd)}")"
[[ -r "${path}" ]] || {
    echo "error: invalid path '${path}'" >&2
    exit 1
}

workdir="${path}"
[[ -d "${path}/" ]] || {
    workdir="$(dirname "${path}")"
    current="$(basename "${path}")"
}
unset path

{ pushd "${workdir}" >/dev/null
  imv -f -s shrink ${current:+-n "${current}"} *
  popd >/dev/null
}
