#!/usr/bin/env bash

# Qemu VMs and runtime location
IMAGESDIR="${QEMU_IMAGES_DIR:-${XDG_STATE_HOME:-${HOME}/.local/state}/qemu}"

# If not symlink just show VMs status and exit
if [[ ! -L "${0}" ]]; then
    printf "%-50s %-10s %s\n" "Name" "PID" "Ports"
    for vm in $(find "${IMAGESDIR}" -type d -maxdepth 1 -exec basename {} \; 2>/dev/null | tail -n +2 | sort); do
        vmpid=$(pgrep --uid ${USER} --full "^qemu.*name\s${vm}\s")
        vmconf="${IMAGESDIR}/${vm}/qemu.cfg"
        [[ -r "${vmconf}" ]] && source "${vmconf}"
        printf "%-50s %-10s %s\n" "${vm}" "${vmpid:--}" "${PORTFWD:--}"
        unset PORTFWD
    done
    exit
fi

# VM info
VMNAME="$(basename ${0})"
VMHOME="${IMAGESDIR}/${VMNAME}"
VMVARS="${VMHOME}/efivars.bin"
VMCONF="${VMHOME}/qemu.cfg"
VMBLOG="${VMHOME}/boot.log"
VMELOG="${VMHOME}/qemu.log"
VMSOCK="${XDG_RUNTIME_DIR:-/run/user/${UID}}/${VMNAME}.sock" # Spice unix socket file name

#============= Settings section ================================
# EFI images, unset to boot in compatibility mode
EFIBIOS="/usr/share/edk2/x64/OVMF_CODE.4m.fd"
EFIVARS="/usr/share/ovmf/x64/OVMF_VARS.4m.fd"
# VM root fs image, can be empty if BASEIMG is set, in such case all fs changes will
# be lost after VM power down (see qemu -snapshot option). In combination with BASEIMG
# will contain only changes to BASEIMG and leave BASEIMG unmodified.
ROOTIMG="${VMHOME}/rootfs.qcow2"
# Other settings
MACHINE=""   # defqult: 'q35', see qemu -machine help
CPU=""       # default: 'host', see qemu -cpu help
SOCKETS=     # default: 1, processors count
CORES=       # default: not set, per socket
THREADS=     # default: not set, per core
RAMSIZE=     # default: 4096, MBytes
AUDIODRV=""  # default: 'alsa', see qemu -audio help
AUDIOHW=""   # default: 'hda', see qemu -audio model=help
VIDEOHW=""   # default: 'qxl', use 'virtio' for Linux guests after installation, see qemu -vga help
BASEIMG=""   # default: not set, base qcow2 image, relative to ${IMAGESDIR}
HEADLESS=    # default: not set, any value will disable Spice connection on startup
SHAREDDIR="" # default: none, shared host <-> guest folder path
PORTFWD=""   # default: not set, port forwarding in form 'hport1:gport1 hport2:gport2 ...'
#============= End of settings section =========================

# Read VM settings
[[ -r "${VMCONF}" ]] && source "${VMCONF}"

# Validate base image (if set)
BASEIMG="${BASEIMG:+${IMAGESDIR}/${BASEIMG}}"
if [[ "${BASEIMG}" && ! -r "${BASEIMG}" ]]; then
    echo "error: invalid base image path, exiting..."
    exit 1
fi

# Host/guest audio driver
if [[ ! "${HEADLESS}" ]]; then
    AUDIODRV="${AUDIODRV:-alsa}"
    #export QEMU_AUDIO_DRV="${AUDIODRV}"
    AUDIOHW="${AUDIOHW:-hda}"
    AUDIO="-audio ${AUDIODRV},model=${AUDIOHW}"
fi
unset AUDIORDV AUDIOHW

# Fix 'VIDEOHW' for headless VM
if [[ "${HEADLESS}" ]]; then
    VIDEOHW="std -display none"
fi

# Port forwarding
for pair in ${PORTFWD}; do
    hport=$(echo ${pair} | awk -F: '{ print $1}')
    gport=$(echo ${pair} | awk -F: '{ print $2}')
    HOSTFWD="${HOSTFWD},hostfwd=tcp::${hport}-:${gport}"
done
unset PORTFWD

# Spice connection
function spice_connect() {
    if [[ $(pgrep --uid ${USER} --full "^qemu.*name\s${VMNAME}\s") ]]; then
        if [[ "${HEADLESS}" ]]; then
            echo "VM is running in headless mode, exiting..."
            exit
        fi
        exec spicy --title="${VMNAME}" --uri="spice+unix://${VMSOCK}"
    fi
}

# Connect to already started VM
spice_connect

# Extra drives (qemu "img", premounted folder, cdrom "iso", floppy "v?fd")
while [[ "${1}" ]]; do
    if [[ -f "${1}" ]]; then
        if [[ "${1}" =~ (.*)\.img$ ]]; then
            DRIVE_EXTRA="${DRIVE_EXTRA} -drive if=virtio,media=disk,file=${1}"
        elif [[ "${1}" =~ (.*)\.iso$ ]]; then
            DRIVE_EXTRA="${DRIVE_EXTRA} -drive if=ide,media=cdrom,readonly=on,file=${1}"
        elif [[ "${1}" =~ (.*)\.v?fd$ ]]; then
            DRIVE_EXTRA="${DRIVE_EXTRA} -drive if=floppy,file=${1}"
        fi
    elif [[ -d "${1}" ]]; then
        DRIVE_EXTRA="${DRIVE_EXTRA} -drive file=fat:rw:${1}"
    else
        ARGS_EXTRA="${ARGS_EXTRA} ${1}"
    fi
    shift
done

# To be sure that images dir exists
mkdir -p "${VMHOME}" || exit 1

# Validate virtual image existence
if [[ "${ROOTIMG}" && ! -r "${ROOTIMG}" ]]; then
    if [[ "${BASEIMG}" ]]; then
        qemu-img create -f qcow2 -b "${BASEIMG}" -F qcow2 "${ROOTIMG}" || exit 1
    elif [[ "${DRIVE_EXTRA}" ]]; then
        echo -n "Enter virtual image size (gigabytes, default: 32G): " && read ROOTSIZE
        qemu-img create -f qcow2 "${ROOTIMG}" ${ROOTSIZE:-32}G || exit 1
    else
        echo "error: image '${ROOTIMG}' not exists and bootable media not specified"
        echo "error: use '${VMNAME} image.iso' or set 'BASEIMG' in '${VMCONF}', exiting..."
        exit 1
    fi
fi

# SMP
SMP="sockets=${SOCKETS:-1}"
[[ "${CORES}" ]] && SMP="${SMP},cores=${CORES}"
[[ "${THREADS}" ]] && SMP="${SMP},threads=${THREADS}"

# EFI bios and vars storage
if [[ "${EFIBIOS}" ]]; then
    if [[ -r "${EFIBIOS}" ]]; then
        DRIVE_EFI="-drive if=pflash,format=raw,readonly=on,file=${EFIBIOS}"
        if [[ ! -r "${VMVARS}" && -r "${EFIVARS}" ]]; then
            cp "${EFIVARS}" "${VMVARS}"
        fi
        DRIVE_EFI="${DRIVE_EFI} -drive if=pflash,format=raw,file=${VMVARS}"
    else
        echo "warning: can't find '${EFIBIOS}' image, booting in BIOS mode"
    fi
fi

# SCSI controller
SCSI0="-device virtio-scsi-pci,id=scsi0"

# Main image
DRIVE_MAIN="${SCSI0} -device scsi-hd,bus=scsi0.0,drive=hd0"
DRIVE_MAIN="${DRIVE_MAIN} -drive id=hd0,if=none,media=disk,format=qcow2,aio=native,cache=none,readonly=off,file"
if [[ ! "${ROOTIMG}" && "${BASEIMG}" ]]; then
    DRIVE_MAIN="${DRIVE_MAIN}=${BASEIMG},snapshot=on"
elif [[ "${ROOTIMG}" ]]; then
    DRIVE_MAIN="${DRIVE_MAIN}=${ROOTIMG}"
else
    echo "error: root image not set, exiting..."
    exit 1
fi

if [[ ! "${HEADLESS}" ]]; then
    SPICE="-device virtio-serial \
-chardev spicevmc,id=vdagent,debug=0,name=vdagent \
-device virtserialport,chardev=vdagent,name=com.redhat.spice.0 \
-chardev spiceport,id=webdav,name=webdav \
-device virtserialport,chardev=webdav,name=org.spice-space.webdav.0 \
-spice unix=on,addr=${VMSOCK},disable-ticketing=on,image-compression=off,gl=on"
fi

# Full QEMU command
QEMUCMD="qemu-system-x86_64 -name ${VMNAME} -nodefaults \
-machine type=${MACHINE:-q35},accel=kvm \
-cpu ${CPU:-host} -smp ${SMP} -m size=${RAMSIZE:-4096} \
-object rng-random,id=rng0,filename=/dev/urandom -device virtio-rng-pci,rng=rng0 \
-rtc base=localtime,clock=host -vga ${VIDEOHW:-qxl} ${SPICE} \
-device qemu-xhci -device usb-kbd -device usb-tablet \
-nic user,model=virtio-net-pci${HOSTFWD} \
-boot order=cda,once=dca ${DRIVE_EFI} ${DRIVE_MAIN} ${DRIVE_EXTRA} \
${AUDIO} -daemonize -D ${VMELOG} ${ARGS_EXTRA}"

# Debug
echo "${QEMUCMD}" | tee "${VMBLOG}"

# Start VM
${QEMUCMD}

# Connect to VM
spice_connect
