#!/usr/bin/env bash

MODEL="pc105"
LAYOUT="us,ru" # ,ua"
OPTIONS="grp:alt_space_toggle,grp_led:scroll,terminate:ctrl_alt_bksp"
DELAY="330"
RATE="25"

setxkbmap -model "${MODEL}" -layout "${LAYOUT}" -option "${OPTIONS}"
xset r rate ${DELAY} ${RATE}
