#!/usr/bin/bash
LANG=C
set -e

THIS="$(basename $(realpath ${BASH_SOURCE[0]}))"

DEF_SINK="$(pamixer --list-sinks | grep 'Running' | awk '{ print $1 }')"
DEF_SINK="${DEF_SINK:-$(pamixer --get-default-sink | tail -1 | awk '{ print $1 }')}"
SINK="${DEF_SINK:+--sink ${DEF_SINK}}"

function get() {
    local level=$(pamixer ${SINK} --get-volume)

    local state="$(pamixer ${SINK} --get-mute)"
    [[ "${state}" == "false" ]] && {
        state="off"
        (( ${level} > 0  )) && state="low"    || true
        (( ${level} > 30 )) && state="middle" || true
        (( ${level} > 70 )) && state="high"   || true
    } || {
        state="muted"
    }

    notify --hint="string:x-canonical-private-synchronous:${THIS}" \
           --hint="int:value:${level}"                             \
           --icon="volume/${state}"                                \
           "${level}%"

    echo "${THIS^}: ${state}" "${level}"
}

function decrease() {
    pamixer ${SINK} --decrease "${1:-5}"
    get
}

function increase() {
    pamixer ${SINK} --increase "${1:-5}"
    get
}

function mute() {
    pamixer ${SINK} --toggle-mute
    get
}

case "${1}" in
    -) decrease "${2}" ;;
    +) increase "${2}" ;;
    m) mute            ;;
    *) get             ;;
esac
