#!/usr/bin/env bash

###
# Example '${WINEPREFIX}/wine.cfg' file
###
#APP_ARCH=
#APP_PATH="Games/Program"
#EXE_FILE="Program.exe"
#EXE_OPTS=

CWD="$(pwd)"

# Detect wine prefix
WINEPREFIX="$(dirname $(realpath ${0}))"

# Load config if any
CONFIG="${APP_CONF:-${WINEPREFIX}/wine.cfg}"
[[ -r "${CONFIG}" ]] && source "${CONFIG}"

# Set wine version
WINEARCH="win${APP_ARCH:-32}"
export WINEARCH WINEPREFIX

( cd "${WINEPREFIX}"
  # Init 'drive_c'
  if [[ ! -d "drive_c" ]]; then
      rm -fr "dosdevices" ".dxvk-installed" ".update-timestamp" *.reg
      wineboot --init && wineboot --end-session
      while [[ ! -f "system.reg" ]]; do sleep 0.1; done
  fi

  # Update prefix folder, remove 'dxvk'
  if [[ ! -f ".update-timestamp" ]]; then
      wineboot --update && wineboot --end-session
      while [[ ! -f "system.reg" ]]; do sleep 0.1; done
      # while read i; do if [[ "${i}" = "system.reg" ]]; then break; fi; done \
      #     < <(inotifywait -e create,open,moved_to --format '%f' --quiet . --monitor)
      [[ -f ".dxvk-installed" ]] && setup_dxvk uninstall --symlink && rm -f ".dxvk-installed"
  fi

  # Install 'dxvk'
  if [[ ! -f ".dxvk-installed" ]]; then
      setup_dxvk install --symlink && touch ".dxvk-installed" || exit 1
      date +%s > ".dxvk-installed"
  fi

  # Start installer/winecfg/winetricks
  if [ -n "${1}" ]; then
      case "${1}" in
          bash)
              shift
              exec bash "${@}"
              ;;
          control)
              shift
              exec wine control "${@}"
              ;;
          regedit)
              shift
              exec regedit "${@}"
              ;;
          winecfg)
              shift
              exec winecfg "${@}"
              ;;
          winetricks)
              shift
              exec winetricks "${@}"
              ;;
          *)
              cd "${CWD}" && exec wine "${@}"
              ;;
      esac
  fi

  [[ -z "${EXE_FILE}" ]] && echo "error: executable not specified, exiting..." && exit 1

  # Start application if specified
  cd "drive_c/${APP_PATH}" &&
      exec wine "${EXE_FILE}" "${EXE_OPTS}" "${@}"
)
