#!/usr/bin/env bash

# Detect wine prefix
WINEPREFIX="$(dirname $(realpath --no-symlinks ${0}))"

# Load config if any
CONFIG="${APPCONF:-${WINEPREFIX}/wine.cfg}"
[[ -r "${CONFIG}" ]] && source "${CONFIG}"

# Set wine version
WINEARCH="win${APPARCH:-32}"
export WINEARCH WINEPREFIX

( cd "${WINEPREFIX}"

  # Setup and update prefix folder
  [[ ! -d "drive_c" ]] && winecfg && setup_dxvk install
  [[ ! -f ".update-timestamp" ]] && wineboot && setup_dxvk install

  # Start installer/winecfg/winetricks
  if [ -n "${1}" ]; then
      case "$1" in
          bash)
              shift
              exec bash "${@}"
              ;;
          regedit)
              shift
              exec regedit "${@}"
              ;;
          winecfg)
              shift
              exec winecfg "${@}"
              ;;
          winetricks)
              shift
              exec winetricks "${@}"
              ;;
          *)
              exec wine "${@}"
              ;;
      esac
  fi

  [[ -z "${EXE_FILE}" ]] && echo "error: executable not specified, exiting..." && exit 1

  # Start application if specified
  cd "drive_c/${APP_PATH}" &&
      exec wine "${EXE_FILE}" "${EXE_OPTS}" "${@}"
)
