#!/usr/bin/env bash

###
# Example '${WINEPREFIX}/game.cfg' file
###
#APP_PATH="Games/Program"
#EXE_FILE="Program.exe"
#EXE_OPTS=

CWD="$(pwd)"

# Detect wine prefix
THIS="${0}"
RELPATH="$(realpath $(dirname ${THIS}))"
if [[ ! -L "${THIS}" ]]; then
    echo "error: '$(basename ${THIS})' assumed to be symlinked inside 'WINEPREFIX'"
    exit 1
fi
while [[ -L "${THIS}" ]]; do
    LINK="$(readlink ${THIS})"
    case "${LINK}" in
        /*)
            RELPATH="$(dirname ${LINK})"
            ;;
        ./*|../*)
            RELPATH="${RELPATH}/$(dirname ${LINK})"
            ;;
    esac
    THIS_BASE="${RELPATH}/$(basename ${LINK})"
    if [[ ! -L "${THIS_BASE}" ]]; then
        break
    fi
    THIS="${THIS_BASE}"
done
export WINEPREFIX="$(realpath $(dirname ${THIS}))"
unset RELPATH LINK THIS THIS_BASE

# Load config if any
CONFIG="${CONFIG:-${WINEPREFIX}/game.cfg}"
[[ -r "${CONFIG}" ]] && source "${CONFIG}"
unset CONFIG

( cd "${WINEPREFIX}"
  # Init 'drive_c'
  if [[ ! -d "drive_c/windows" ]]; then
      rm -fr "dosdevices" ".dxvk-installed" ".update-timestamp" *.reg
      wineboot --init && wineboot --end-session
      while [[ ! -f "system.reg" ]]; do sleep 0.1; done
  fi

  # Update prefix folder, remove 'dxvk'
  if [[ ! -f ".update-timestamp" ]]; then
      wineboot --update && wineboot --end-session
      while [[ ! -f "system.reg" ]]; do sleep 0.1; done
      [[ -f ".dxvk-installed" ]] && setup_dxvk uninstall --symlink && rm -f ".dxvk-installed"
  fi

  # Install 'dxvk'
  if [[ ! -f ".dxvk-installed" ]]; then
      setup_dxvk install --symlink && touch ".dxvk-installed" || exit 1
      date +%s > ".dxvk-installed"
  fi

  # Start installer/winecfg/winetricks
  if [ -n "${1}" ]; then
      case "${1}" in
          bash)
              shift
              exec bash "${@}"
              ;;
          control)
              shift
              exec wine control "${@}"
              ;;
          regedit)
              shift
              exec regedit "${@}"
              ;;
          winecfg)
              shift
              exec winecfg "${@}"
              ;;
          winetricks)
              shift
              exec winetricks "${@}"
              ;;
          *)
              cd "${CWD}" && exec wine "${@}"
              ;;
      esac
  fi

  [[ -z "${EXE_FILE}" ]] && echo "error: executable not specified, exiting..." && exit 1

  # Start application if specified
  cd "drive_c/${APP_PATH}" &&
      exec wine "${EXE_FILE}" "${EXE_OPTS}" "${@}"
)
