#!/usr/bin/env bash

log="${XDG_LOG_HOME:-/tmp}/xsel.log"

# Parse arguments
args=()
while [[ "${1}" ]]; do
    case "${1}" in
    -d | -display)
        shift
        args+=("--display" "${1}")
        ;;
    -h | -help)
        exec xsel --help
        ;;
    -i | -input)
        args+=("--input")
        ;;
    -o | -out)
        args+=("--output")
        ;;
    -quiet)
        args+=("--nodetach")
        ;;
    -selection)
        shift
        case "$1" in
        clipboard)
            args+=("--clipboard")
            ;;
        primary)
            args+=("--primary")
            ;;
        secondary)
            args+=("--secondary")
            ;;
        *)
            echo "error: invalid selection '${1}'"
            exit 1
            ;;
        esac
        ;;
    -verbose)
        args+=("--verbose")
        ;;
    -v | -version)
        exec xsel --version
        ;;
    *) ;;
    esac
    shift
done

set -- "${args[@]}"

exec xsel "${@}" 2>"${log}"
